/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sirenko (https://sketchfab.com/sirenko)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ball-4a0f6fd907a2481db570e1564e12c807
title: Ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import FILE from './soccer_ball.gltf';

export default function Soccer_ball({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(FILE)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FILE)
